# Generated by Django 5.0.1 on 2024-02-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('delivery_challan_number', models.CharField(max_length=50)),
                ('purchase_order_number', models.CharField(max_length=50)),
                ('checked_out', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('delivery_challan_number', models.CharField(max_length=50)),
                ('checked_by', models.CharField(max_length=100)),
                ('check_date', models.DateField()),
                ('check_time', models.TimeField()),
                ('inspection_passed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inspection_type', models.CharField(max_length=100)),
                ('inspection_details', models.TextField(blank=True, null=True)),
                ('defects_found', models.TextField(blank=True, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclemsapp.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Quality Check',
                'verbose_name_plural': 'Vehicle Quality Checks',
            },
        ),
    ]
